# Generated by Django 5.1.7 on 2025-03-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_address_order_city_order_email_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Zip',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
