# Generated by Django 5.1.7 on 2025-03-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Zip',
            new_name='zip',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='', max_length=200),
        ),
    ]
